### ISSUE TITLE
Translation Progress

### ISSUE THREAD

**Issue by LLLgoyour** [opensource-way-chinese-translation/the_open_source_way-guidebook-2.0-zh#20]
# Checklist 清单表
## Attracting Users
- [x] attracting_users
- [ ] communication_norms_in_open_source_software_projects
- [ ] to_build_diverse_open_source_communities_make_them_inclusive_first
## Getting Started
- [ ] community_101_understanding_joining,_or_forming_a_new_community
- [x] creating_an_open_source_product_strategy (Cubik65536, not finished yet)
- [x] getting_started
- [ ] new_project_checklist
## Growing Contributors
- [ ] community_manager_self-care
- [ ] community_roles
- [ ] creating_a_culture_of_mentorship
- [ ] essentials_of_building_a_community
- [ ] from_users_to_contributors
- [ ] growing_contributors
- [ ] onboarding
- [ ] project_and_community_governance
- [ ] what_is_a_contribution
## Guiding Participants
- [x] guiding_participants
- [x] why_do_people_participate_in_open_source_communities
## Measuring Success
- [x] announcing_software_releases (LLLgoyour, not finished yet)
- [ ] defining_healthy_communities
- [ ] measuring_success
- [ ] understanding_community_metrics
## Presenting the Open Source Way
- [ ] a_community_of_practice_always_rebuilding_itself
- [ ] presenting_the_open_source_way
- [ ] structure_of_this_guide
- [x] the_shape_of_things (KevinZonda, not finished yet)
## Others
- [ ] contributors
- [ ] cover_and_table_of_contents (index table)

**Comment by Cubik65536** [comment]
incomplete标签并非是为此设置的，这个issue不打标签即可
